### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by austincollinpena** [joeshaw/ecp-ja3#1]
Ever encounter any internal server errors? Running with TLS on so not sure what's up

**Comment by joeshaw** [comment]
Hmm, no, there's not a lot that can go wrong here!  I'm assuming you're running on Compute@Edge and not in the local development environment, Viceroy?

You could try log-tailing the service to see if there are panics or other runtime-related issues happening there.  If a 500 is happening, it could be a panic before the handler gets executed, but I can't imagine why.

**Comment by austincollinpena** [comment]
Yeah that's true. TBH I just moved to Rust for now. I'm bummed by that but I'll hit up support.

The handler works fine except when I'm getting the JA3.

On a separate note... are you doing any normalizing of JA3's to counter Chrome's random implementation? https://hnull.org/2022/12/01/sorting-out-randomized-tls-fingerprints/

**Comment by joeshaw** [comment]
I hadn't seen this, but I'll take a look at it.  My original plan was to implement the JA3 generation myself, but I was able to farm it out to a third party library, so normalization will probably need to go upstream into that library.

I just pushed a commit which updates the tinygo build script and updates the Go SDK to the latest version.  Feel free to give that a shot, but I don't expect it to change anything.

**Comment by austincollinpena** [comment]
What was the third party library? I'm currently using Fastly for this but would be interested in more control.

**Comment by joeshaw** [comment]
https://github.com/AGWA/tlshacks

Blog post about it: https://www.agwa.name/blog/post/parsing_tls_client_hello_with_cryptobyte

**Comment by austincollinpena** [comment]
Dang, I never saw a link to that repo. That would have saved me some time haha. Thanks for sharing it.
